var actionArray = [

	'Dropping a chandelier on your enemies and riding the rope up.',
	'Sexting.',
	'Laying an egg.',
	'Getting naked and watching Nickelodeon.',
	'Pretending to care.',
	'Sharing needles.',
	'Whipping it out.',
	'Eating all of the cookies before the AIDS bake-sale.',
	'Swooping.',
	'Taking off your shirt.',
	'Bingeing and purging.',
	'Being on fire.',
	'Picking up girls at the abortion clinic.',
	'Not reciprocating oral sex.',
	'Waterboarding.',
	'Actually taking candy from a baby.',
	'Switching to Geico.',
	'Peeing a little bit.',
	'Being rich.',
	'Copping a feel.',
	'Doing the right thing.',
	'Fingering.',
	'Scalping.',
	'Stifling a giggle at the mention of Hutus and Tutsis.',
	'"Tweeting."',
	'Expecting a burp and vomiting on the floor.',
	'Scrubbing under the folds.',
	'Licking things to claim them as your own.',
	'Finger painting.',
	'Dying of dysentery.',
	'Cuddling.',
	'Riding off into the sunset.',
	'Eating the last known bison.',
	'Forgetting the Alamo.',
	'Wiping her butt.',
	'Getting really high.',
	'Praying the gay away.',
	'Frolicking.',
	'Prancing.',
	'Dwarf tossing.',
	'Flash flooding.',
	'Dry heaving.',
	'Breaking out into song and dance.',
	'Waking up half-naked in a Denny\'s parking lot.',
	'Waiting ‘til marriage.',
	'Re-gifting.',
	'Autocannibalism.',
	'Same-sex ice dancing.',
	'Cheating in the Special Olympics.',
	'Pooping back and forth. Forever.',
	'YOU MUST CONSTRUCT ADDITIONAL PYLONS.',
	'Being fabulous.',
	'Necrophilia.',
	'Chivalry.',
	'Passing a kidney stone.',
	'Masturbation.',
	'Queefing.',
	'Concealing a boner.',
	'Surprise sex!',
	'Drinking alone.',
	'Soiling oneself.',
	'Child abuse.',
	'Pulling out.',
	'Doin\' it in the butt.',
	'Feeding Rosie O\'Donnell.',
	'Teaching a robot to love.',
	'Wearing underwear inside-out to avoid doing laundry.',
	'When you fart and a little bit comes out.',
	'Getting drunk on mouthwash.',
	'Giving 110 percent.',
	'Being marginalized.',
	'Seduction.',
	'Making a pouty face.',
	'Exchanging pleasantries.',
	'Parting the Red Sea.',
	'A snapping turtle biting the tip of your penis.',
	'Jerking off into a pool of children\'s tears.',
	'Being a motherfucking sorcerer.',
	'Being a dick to children.',
	'Booby-trapping the house to foil burglars.',
	'Dying.',
	'Apologizing.',
	'Farting and walking away.',
	'Beating your wives.',
	'Being a dinosaur.',
	'Coughing into a vagina.',
	'Dancing with a broom.',
	'Deflowering the princess.',
	'Eating an albino.',
	'Fabricating statistics.',
	'Finding a skeleton.',
	'Getting abducted by Peter Pan.',
	'Getting in her pants, politely.',
	'Leveling up.',
	'Literally eating shit.',
	'Making the penises kiss.',
	'Overpowering your father.',
	'Pistol-whipping a hostage.',
	'Revenge fucking.',
	'Ripping into a man\'s chest and pulling out his still-beating heart.',
	'Scrotum tickling.',
	'Being a busy adult with many important things to do.',
	'Tripping balls.',
	'Existing.',
	'Mooing.',
	'Swiftly achieving orgasm.',
	'Subduing a grizzly bear and making her your wife.',
	'Rising from the grave.',
	'Taking a man\'s eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.',
	'Whining like a little bitch.',
	'Pumping out a baby every nine months.',
	'Finding Waldo.',
	'Upgrading homeless people to mobile hotspots.',
	'Wearing an octopus for a hat.',
	'Living in a trashcan.',
	'Getting hilariously gang-banged by the Blue Man Group.',
	'Making a friend.',
	'Being awesome at sex.',
	'Dining with cardboard cutouts of the cast of Friends.',
	'Beefin\' over turf.',
	'Whipping a disobedient slave.',
	'Dying alone and in pain.',
	'Not having sex.',
	'Running naked through a mall, pissing and shitting everywhere.',
	'The systematic destruction of an entire people and their way of life.',
	'Going around punching people.',
	'Chugging a lava lamp.',
	'Having sex on top of a pizza.',
	'Shutting the fuck up.',
	'Putting an entire peanut butter and jelly sandwich into the VCR.',
	'Spending lots of money.',
	'Not contributing to society in any meaningful way.',
	'Screaming like a maniac.',
	'Filling every orifice with butterscotch pudding.',
	'Eating Tom Selleck\'s mustache to gain his powers.',
	'Buying the right pants to be cool.',
	'Slapping a racist old lady.',
	'Jumping out at people.',
	'Vomiting mid-blowjob.',
	'Having shotguns for legs.',
	'Letting everyone down.',
	'Getting your dick stuck in a Chinese finger trap with another dick.',
	'Fisting.',
	'Blowing some dudes in an alley.',
	'Drinking ten 5-hour ENERGY; to get fifty continuous hours of energy.',
	'Sneezing, farting, and coming at the same time.',
	'sudo make me a sandwich.',
	'Going over niagra falls.'

]

module.exports = actionArray;