var blackcards = [
 
	"cahbot Don't forget to write down my new email address: _@_.com.",
	"cahbot You. Me. _. Now.",
	"cahbot 911, what's your emergency?",
	"cahbot Oh no! _! My only weakness!",
	"cahbot GO GO GADGET -what!!",
	"cahbot This workplace has been 0 days without _.",
	"cahbot I couldn't find a condom, so I had to use _ instead.",
	"cahbot On a scale of _ to _, how would you rate your pain?",
	"cahbot Yeah, I had to break with him. He kept using '_' as a euphemism for having sex.",
	"cahbot I kissed a _ and I liked it!",
	"cahbot The judge acquitted me because _ isn't technically a crime.",
	"cahbot Do you know why I pulled you over?",
	"cahbot Six Flag's new thrill ride lets you experience _ at 120 miles per hour.",
	"cahbot Hi, we are from the church of _, do you have a moment to talk about _?",
	"cahbot I'm all over it, like _ on _ .",
	"cahbot _ and _: Still a better love story than Twilight.",
	"cahbot On a scale of _ to _, exactly how screwed are we?",
	"cahbot Would the owner of _ please come to the front desk?",
	"cahbot Why do I have a boner?",
	"cahbot And on the 8th day, God was going to create _, but then He decided, 'Nah, better not.'",
	"cahbot During his short-lived boxing career, the Messiah went by the name Jesus ' _ ' Christ.",
	"cahbot _ vs. _: The new SyFy Original Movie.",
	"cahbot I just filled my 1.5 Tb hard drive with pictures of _.",
	"cahbot It is said that the Inuit have over 40 different words for _.",
	"cahbot _? There's an app for that?",
	"cahbot Why can't I sleep at night?",
	"cahbot What's that smell?",
	"cahbot I've got 99 problems, but _ ain't one",
	"cahbot Maybe she's born with it.  Maybe it's _.",
	"What's the next Happy Meal toy?",
	"cahbot Anthropologists have recently discovered a primitive tribe that worships _.",
	"cahbot It's a pity that kids these days are all getting involved with _.",
	"cahbot During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of _.",
	"cahbot Alternative medicine is now embracing the curative powers of _.",
	"cahbot And the Academy Award for _ goes to _.",
	"cahbot What's that sound?",
	"cahbot What ended my last relationship?",
	"cahbot MTV's new reality show features eight washed-up celebrities living with _.",
	"cahbot I drink to forget _.",
	"cahbot I'm sorry professor, but I couldn't complete my homework because of _.",
	"cahbot What is Batman's guilty pleasure?",
	"cahbot This is the way the world ends, not with a bang but with _.",
	"cahbot What's a girl's best friend?",
	"cahbot TSA guidelines now prohibit _ on airplanes.",
	"cahbot _.  That's how I want to die.",
	"cahbot For my next trick, I will pull _ out of _.",
	"cahbot In the new Disney Channel Original Movie, Hannah Montana struggles with _ for the first time.",
	"cahbot _ is a slippery slope that leads to _.",
	"cahbot What does Dick Cheney prefer?",
	"cahbot Dear Abby, I'm having some trouble with _ and would like your advice.",
	"cahbot Instead of coal, Santa now gives the bad children _.",
	"cahbot What's the most emo?",
	"cahbot In 1,000 years when paper money is but a distant memory, _ will be our currency.",
	"cahbot What's the next superhero/sidekick duo?",
	"cahbot In M. Night Shyamalan's new movie, Bruce Willis discovers that _ had really been _ all along.",
	"cahbot A romantic, candlelit dinner would be incomplete without _.",
	"cahbot _.  Becha can't have just one!",
	"cahbot White people like _.",
	"cahbot _.  High five, bro.",
	"cahbot Next from J.K. Rowling: Harry Potter and the Chamber of _.",
	"cahbot BILLY MAYS HERE FOR _.",
	"cahbot In a world ravaged by _, our only solace is _ War!",
	"cahbot _ What is it good for?",
	"cahbot During sex, I like to think about _.",
	"cahbot What are my parents hiding from me?",
	"cahbot What will always get you laid?",
	"cahbot In L.A. County Jail, word is you can trade 200 cigarettes for _.",
	"cahbot What did I bring back from Mexico?",
	"cahbot What don't you want to find in your Chinese food?",
	"cahbot What will I bring back in time to convince people that I am a powerful wizard?",
	"cahbot How am I maintaining my relationship status?",
	"cahbot _.  It's a trap!",
	"cahbot Coming to Broadway this season, _: The Musical.",
	"cahbot While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _.",
	"cahbot After the earthquake, Sean Penn brought _ to the people of Haiti.",
	"cahbot Next on ESPN2, the World Series of _.",
	"cahbot Step 1: _.  Step 2: _.  Step 3: Profit.",
	"cahbot Rumor has it that Vladimir Putin's favorite dish is _ stuffed with _.",
	"cahbot But before I kill you, Mr. Bond, I must show you _.",
	"cahbot What gives me uncontrollable gas?",
	"cahbot What do old people smell like?",
	"cahbot The class field trip was completely ruined by _.",
	"cahbot When Pharaoh remained unmoved, Moses called down a Plague of _.",
	"cahbot What's my secret power?",
	"cahbot What's there a ton of in heaven?",
	"cahbot What would grandma find disturbing, yet oddly charming?",
	"cahbot I never truly understood _ until I encountered _.",
	"cahbot What did the U.S. airdrop to the children of Afghanistan?",
	"cahbot What helps Obama unwind?",
	"cahbot What did Vin Diesel eat for dinner?",
	"cahbot _: good to the last drop.",
	"cahbot Why am I sticky?",
	"cahbot What gets better with age?",
	"cahbot _: kid-tested, mother-approved.",
	"cahbot What's the crustiest?",
	"cahbot What's Teach for America using to inspire inner city students to succeed?",
	"cahbot Studies show that lab rats navigate mazes 50% faster after being exposed to _.",
	"cahbot Life for American Indians was forever changed when the White Man introduced them to _.",
	"cahbot Make a haiku.",
	"cahbot I do not know with what weapons World War III will be fought, but World War IV will be fought with _.",
	"cahbot Why do I hurt all over?",
	"cahbot What am I giving up for Lent?",
	"cahbot In Michael Jackson's final moments, he thought about _.",
	"cahbot In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on _.",
	"cahbot When I am President of the United States, I will create the Department of _.",
	"cahbot Lifetime presents _, the story of _.",
	"cahbot When I am a billionaire, I shall erect a 50-foot statue to commemorate _.",
	"cahbot When I was tripping on acid, _ turned into _.",
	"cahbot That's right, I killed _. How, you ask?  _.",
	"cahbot What's my anti-drug?",
	"cahbot What never fails to liven up the party?",
	"cahbot What's the new fad diet?",
	"cahbot Major League Baseball has banned _ for giving players an unfair advantage.",
	"cahbot My plan for world domination begins with _.",
	"cahbot The CIA now interrogates enemy agents by repeatedly subjecting them to _.",
	"cahbot Dear Sir or Madam, We regret to inform you that the Office of _ has denied your request for _."
	"cahbot n Rome, there are whisperings that the Vatican has a secret room devoted to _.",
	"cahbot Science will never explain _.",
	"cahbot When all else fails, I can always masturbate to _.",
	"cahbot I learned the hard way that you can't cheer up a grieving friend with _.",
	"cahbot In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated _.",
	"cahbot An international tribunal has found _ guilty of _.",
	"cahbot The socialist governments of Scandinavia have declared that access to _ is a basic human right.",
	"cahbot In his new self-produced album, Kanye West raps over the sounds of _.",
	"cahbot What's the gift that keeps on giving?",
	"cahbot Next season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only _ and his wits.",
	"cahbot When I pooped, what came out of my butt?",
	"cahbot In the distant future, historians will agree that _ marked the beginning of America's decline.",
	"cahbot In a pinch, _ can be a suitable substitute for _.",
	"cahbot What has been making life difficult at the nudist colony?",
	"cahbot Michael Bay's new three-hour action epic pits _ against _.",
	"cahbot And I would have gotten away with it, too, if it hadn't been for _.",
	"cahbot What brought the orgy to a grinding halt?",
	"cahbot During his midlife crisis, my dad got really into _.",
	"cahbot _ would be woefully incomplete without _.",
	"cahbot Before I run for president, I must destroy all evidence of my involvement with _.",
	"cahbot This is your captain speaking. Fasten your seatbelts and prepare for _.",
	"cahbot In his newest and most difficult stunt, David Blaine must escape from _.",
	"cahbot The Five Stages of Grief: denial, anger, bargaining, _, and acceptance.",
	"cahbot My mom freaked out when she looked at my browser history and found _.com/_.",
	"cahbot Members of New York's social elite are paying thousands of dollars just to experience _.",
	"cahbot This month's Cosmo: _",
	"cahbot Spice up your sex life by bringing _ into the bedroom!",
	"cahbot Little Miss Muffet Sat on a tuffet, Eating her curds and _.",
	"cahbot If God didn't want us to enjoy _, he wouldn't have given us _.",
	"cahbot My country, 'tis of thee, sweet land of _.",
	"cahbot After months of debate, the Occupy Wall Street General Assembly could only agree on &#34;",
	"cahbot More _!",
	"cahbot I spent my whole life working toward _, only to have it ruined by _.",
	"cahbot Next time on Dr. Phil: How to talk to your child about _.",
	"cahbot Only two things in life are certain: death and _.",
	"cahbot Everyone down on the ground!",
	"cahbot  We don't want to hurt anyone. We're just here for _.",
	"cahbot The healing process began when I joined a support group for victims of _.",
	"cahbot The votes are in, and the new high school mascot is _.",
	"cahbot Charades was ruined for me forever when my mom had to act out _.",
	"cahbot Before _, all we had was _.",
	"cahbot Tonight on 20/20: What you don't know about _ could kill you.",
	"cahbot You haven't truly lived until you've experienced _ and _ at the same time.",
	"cahbot A successful job interview begins with a firm handshake and ends with _.",
	"cahbot Lovin' you is easy 'cause you're _.",
	"cahbot My life is ruled by a vicious cycle of _ and _.",
	"cahbot The blind date was going horribly until we discovered our shared interest in _.",
	"cahbot _. Awesome in theory, kind of a mess in practice.",
	"cahbot I'm not like the rest of you. I'm too rich and busy for _.",
	"cahbot In the seventh circle of Hell, sinners must endure _ for all eternity.",
	"cahbot _: Hours of fun. Easy to use. Perfect for _!",
	"cahbot What left this stain on my couch?",
	"cahbot Call the law offices of Goldstein & Goldstein, because no one should have to tolerate _ in the workplace.",
	"cahbot When you get right down to it, _ is just _.",
	"cahbot Turns out that _-Man was neither the hero we needed nor wanted.",
	"cahbot As part of his daily regimen, Anderson Cooper sets aside 15 minutes for _.",
	"cahbot Money can't buy me love, but it can buy me _.",
	"cahbot With enough time and pressure, _ will turn into _.",
	"cahbot And what did you bring for show and tell?",
	"cahbot During high school, I never really fit in until I found _ club.",
	"cahbot Hey, baby, come back to my place and I'll show you _.",
	"cahbot After months of practice with _, I think I'm finally ready for _.",
	"cahbot To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of _.",
	"cahbot Finally! A service that delivers _ right to your door.",
	"cahbot My gym teacher got fired for adding _ to the obstacle course.",
	"cahbot Having problems with _? Try _!",
	"cahbot As part of his contract, Prince won't perform without _ in his dressing room.",
	"cahbot Listen, son. If you want to get involved with _, I won't stop you. Just steer clear of _."

]

module.exports = blackcards;