var whatArray = [

	'A Gypsy curse.',
	'A moment of silence.',
	'A sausage festival.',
	'Famine.',
	'Flesh-eating bacteria.',
	'Flying sex snakes.',
	'Not giving a shit about the Third World.',
	'Sexting.',
	'A drive-by shooting.',
	'A time travel paradox.',
	'Authentic Mexican cuisine.',
	'Bling.',
	'Crippling debt.',
	'Daddy issues.',
	'The Donald Trump Seal of Approval™.',
	'Full frontal nudity.',
	'Hormone injections.',
	'Public ridicule.',
	'Boogers.',
	'The inevitable heat death of the universe.',
	'The miracle of childbirth.',
	'The Rapture.',
	'White privilege.',
	'Wifely duties.',
	'AXE Body Spray.',
	'The Blood of Christ.',
	'Horrifying laser hair removal accidents.',
	'BATMAN!!!',
	'Agriculture.',
	'A robust mongoloid.',
	'Natural selection.',
	'Coat hanger abortions.',
	'Michelle Obamas arms.',
	'The World of Warcraft.',
	'Obesity.',
	'A homoerotic volleyball montage.',
	'Lockjaw.',
	'A mating display.',
	'Testicular torsion.',
	'All-you-can-eat shrimp for $4.99.',
	'Dominos™ Oreo™ Dessert Pizza.',
	'Hot cheese.',
	'Raptor attacks.',
	'Smegma.',
	'Alcoholism.',
	'The Care Bear Stare.',
	'Oversized lollipops.',
	'Self-loathing.',
	'Half-assed foreplay.',
	'The Holy Bible.',
	'German dungeon porn.',
	'Teenage pregnancy.',
	'Leaving an awkward voicemail.',
	'Uppercuts.',
	'An erection that lasts longer than four hours.',
	'My genitals.',
	'Science.',
	'Flightless birds.',
	'A good sniff.',
	'A balanced breakfast.',
	'Historically black colleges.',
	'A clandestine butt scratch.',
	'Passive-aggressive Post-it notes.',
	'Home video of Oprah sobbing into a Lean Cuisine.',
	'Nocturnal emissions.',
	'My humps.',
	'Powerful thighs.',
	'Winking at old people.',
	'A gentle caress of the inner thigh.',
	'Sexual tension.',
	'The forbidden fruit.',
	'Fancy Feast.',
	'Sweet, sweet vengeance.',
	'A gassy antelope.',
	'Kamikaze pilots.',
	'The homosexual agenda.',
	'A falcon with a cap on its head.',
	'Getting so angry that you pop a boner.',
	'Free samples.',
	'A big hoopla about nothing.',
	'The Three-Fifths compromise.',
	'Lactation.',
	'World peace.',
	'Chutzpah.',
	'Inappropriate yodeling.',
	'Puberty.',
	'An asymmetric boob job.',
	'Vigorous jazz hands.',
	'Glenn Beck catching his scrotum on a curtain hook.',
	'GoGurt.',
	'A sad handjob.',
	'Exactly what you\'d expect.',
	'Adderall™',

]

module.exports = whatArray;