var whatArray = [

	'A Gypsy curse.',
	'A moment of silence.',
	'A sausage festival.',
	'Famine.',
	'Flesh-eating bacteria.',
	'Flying sex snakes.',
	'Not giving a shit about the Third World.',
	'Sexting.',
	'A drive-by shooting.',
	'A time travel paradox.',
	'Authentic Mexican cuisine.',
	'Bling.',
	'Crippling debt.',
	'Daddy issues.',
	'The Donald Trump Seal of Approval™.',
	'Full frontal nudity.',
	'Hormone injections.',
	'Public ridicule.',
	'Boogers.',
	'The inevitable heat death of the universe.',
	'The miracle of childbirth.',
	'The Rapture.',
	'White privilege.',
	'Wifely duties.',
	'AXE Body Spray.',
	'The Blood of Christ.',
	'Horrifying laser hair removal accidents.',
	'BATMAN!!!',
	'Agriculture.',
	'A robust mongoloid.',
	'Natural selection.',
	'Coat hanger abortions.',
	'Michelle Obamas arms.',
	'The World of Warcraft.',
	'Obesity.',
	'A homoerotic volleyball montage.',
	'Lockjaw.',
	'A mating display.',
	'Testicular torsion.',
	'All-you-can-eat shrimp for $4.99.',
	'Dominos™ Oreo™ Dessert Pizza.',
	'Hot cheese.',
	'Raptor attacks.',
	'Smegma.',
	'Alcoholism.',
	'The Care Bear Stare.',
	'Oversized lollipops.',
	'Self-loathing.',
	'Half-assed foreplay.',
	'The Holy Bible.',
	'German dungeon porn.',
	'Teenage pregnancy.',
	'Leaving an awkward voicemail.',
	'Uppercuts.',
	'An erection that lasts longer than four hours.',
	'My genitals.',
	'Science.',
	'Flightless birds.',
	'A good sniff.',
	'A balanced breakfast.',
	'Historically black colleges.',
	'A clandestine butt scratch.',
	'Passive-aggressive Post-it notes.',
	'Home video of Oprah sobbing into a Lean Cuisine.',
	'Nocturnal emissions.',
	'My humps.',
	'Powerful thighs.',
	'Winking at old people.',
	'A gentle caress of the inner thigh.',
	'Sexual tension.',
	'The forbidden fruit.',
	'Fancy Feast.',
	'Sweet, sweet vengeance.',
	'A gassy antelope.',
	'Kamikaze pilots.',
	'The homosexual agenda.',
	'A falcon with a cap on its head.',
	'Getting so angry that you pop a boner.',
	'Free samples.',
	'A big hoopla about nothing.',
	'The Three-Fifths compromise.',
	'Lactation.',
	'World peace.',
	'Chutzpah.',
	'Inappropriate yodeling.',
	'Puberty.',
	'An asymmetric boob job.',
	'Vigorous jazz hands.',
	'Glenn Beck catching his scrotum on a curtain hook.',
	'GoGurt.',
	'A sad handjob.',
	'Exactly what you\'d expect.',
	'Adderall™',
	'Embryonic stem cells.',
	'Tasteful sideboob.',
	'Panda sex.',
	'An icepick lobotomy.',
	'Mouth herpes.',
	'Third base.',
	'Incest.',
	'Golden showers.',
	'Emotions.',
	'Pabst Blue Ribbon.',
	'The placenta.',
	'Spontaneous human combustion.',
	'Old-people smell.',
	'My inner demons.',
	'A Super Soaker full of cat pee.',
	'The chronic.',
	'Cockfights.',
	'Friendly fire.',
	'A disappointing birthday party.',
	'An M. Night Shyamalan plot twist.',
	'Jew-fros.',
	'Mutually-assured destruction.',
	'Yeast.',
	'Catapults.',
	'The Hustle.',
	'The Force.',
	'Intelligent design.',
	'Loose lips.',
	'Pictures of boobs.',
	'Scientology.',
	'Penis envy.',
	'Two midgets shitting into a bucket.',
	'Crystal meth.',
	'Serfdom.',
	'Stranger danger.',
	'A Bop It.',
	'Shaquille O\'Neal\'s acting career.',
	'Vigilante justice.',
	'Overcompensation.',
	'Pixelated bukkake.',
	'A lifetime of sadness.',
	'Racism.',
	'Sunshine and rainbows.',
	'Lance Armstrong\'s missing testicle.',
	'Attitude.',
	'Leprosy.',
	'Gloryholes.',
	'Nipple blades.',
	'The heart of a child.',
	'Puppies!',
	'Dental dams.',
	'Toni Morrison\'s vagina.',
	'The taint; the grundle; the fleshy fun-bridge.',
	'Active listening.',
	'Ethnic cleansing.',
	'The invisible hand.',
	'Unfathomable stupidity.',
	'Euphoria by Calvin Klein.',
	'Erectile dysfunction.',
	'My collection of high-tech sex toys.',
	'Tentacle porn.',
	'Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts.',
	'Too much hair gel.',
	'Seppuku.',
	'Charisma.',
	'A look-see.',
	'Menstruation.',
	'A salty surprise.',
	'The violation of our most basic human rights.',
	'Lunchables.',
	'Fiery poops.',
	'Another goddamn vampire movie.',
	'Tangled Slinkys.',
	'The true meaning of Christmas.',
	'Estrogen.',
	'A zesty breakfast burrito.',
	'That thing that electrocutes your abs.',
	'A bleached asshole.',
	'Cybernetic enhancements.',
	'Smallpox blankets.',
	'Classist undertones.',
	'Edible underpants.',
	'Viagra.',
	'Soup that is too hot.',
	'Five-Dollar Footlongs.',
	'Dick fingers.',
	'Multiple stab wounds.',
	'Anal beads.',
	'Civilian casualties.',
	'Horse meat.',
	'A really cool hat.',
	'A stray pube.',
	'A can of whoop-ass.',
	'A windmill full of corpses.',
	'A death ray.',
	'The glass ceiling.',
	'A cooler full of organs.',
	'The American Dream.',
	'Keg stands.',
	'Take-backsies.',
	'Dead babies.',
	'Foreskin.',
	'Saxophone solos.',
	'Firing a rifle into the air while balls deep in a squealing hog.',
	'Eugenics.',
	'My relationship status.',
	'Bees?',
	'Harry Potter erotica.',
	'College.',
	'8 oz. of sweet Mexican black-tar heroin.',
	'Dead parents.',
	'Object permanence.',
	'Opposable thumbs.',
	'Racially-biased SAT questions.',
	'Jibber-jabber.',
	'Chainsaws for hands.',
	'Child beauty pageants.',
	'Explosions.',
	'Sniffing glue.',
	'Repression.',
	'Roofies.',
	'My vagina.',
	'Assless chaps.',
	'A murder most foul.',
	'The Trail of Tears.',
	'Hope.',
	'A micropenis.',
	'My soul.',
	'A hot mess.',
	'An Oedipus complex.',
	'Global warming.',
	'New Age music.',
	'Hot Pockets.',
	'Vehicular manslaughter.',
	'Women\'s suffrage.',
	'A defective condom.',
	'The Virginia Tech Massacre.',
	'Heteronormativity.',
	'Road head.',
	'Spectacular abs.',
	'Figgy pudding.',
	'A mopey zoo lion.',
	'A bag of magic beans.',
	'Poor life choices.',
	'My sex life.',
	'Auschwitz.',
	'A thermonuclear detonation.',
	'The clitoris.',
	'The Big Bang.',
	'Land mines.',
	'The Dance of the Sugar Plum Fairy.',
	'Man meat.',
	'Me time.',
	'The Underground Railroad.',
	'Poorly-timed Holocaust jokes.',
	'A sea of troubles.',
	'Lumberjack fantasies.',
	'Natural male enhancement.',
	'Genital piercings.',
	'Sexy pillow fights.',
	'Balls.',
	'Friction.',
	'The Tempur-Pedic Swedish Sleep System.',
	'Hurricane Katrina.',
	'The folly of man.',
	'Pterodactyl eggs.',
	'Team-building exercises.',
	'A brain tumor.',
	'Cards Against Humanity.',
	'Fear itself.',
	'A foul mouth.',
	'A big black dick.',
	'A beached whale.',
	'A bloody pacifier.',
	'A crappy little hand.',
	'A low standard of living.',
	'A nuanced critique.',
	'Panty raids.',
	'A passionate Latino lover.',
	'A rival dojo.',
	'A web of lies.',
	'A woman scorned.',
	'Clams.',
	'Appreciative snapping.',
	'Shaft.',
	'Nubile slave boys.',
	'Suicidal thoughts.',
	'Dorito breath.',
	'Enormous Scandinavian women.',
	'Gandalf.',
	'Genetically engineered super-soldiers.',
	'George Clooney\'s musk.',
	'Gladiatorial combat.',
	'Good grammar.',
	'Hipsters.',
	'Historical revisionism.',
	'Insatiable bloodlust.',
	'Just the tip.',
	'Mad hacking-sack skills. (think Noah and Owen)',
	'Mad hacky-sack skills.',
	'Media coverage.',
	'Medieval Times Dinner and Tournament.',
	'Moral ambiguity.',
	'My machete.',
	'One thousand Slim Jims.',
	'Ominous background music.',
	'Quiche.',
	'Quivering jowls.',
	'Sexual humiliation.',
	'Sexy Siamese twins.',
	'Slow motion.',
	'Space muffins.',
	'Statistically validated stereotypes.',
	'Sudden Poop Explosion Disease.',
	'The boners of the elderly.',
	'The economy.',
	'The Gulags.',
	'The harsh light of day.',
	'The shambling corpse of Larry King.',
	'The hiccups.',
	'The four arms of Vishnu.',
	'Words, words, words.',
	'Zeus\'s sexual appetites.',
	'A bigger, blacker dick.',
	'The mere concept of Applebee\'s.',
	'A sad fat dragon with no friends.',
	'Catastrophic urethral trauma.',
	'Hillary Clinton\'s death stare.',
	'A pinata full of scorpions.',
	'Daddy\'s belt.',
	'Double penetration.',
	'Weapons-grade plutonium.',
	'Some really fucked-up shit.',
	'The mixing of the races.',
	'Scrotal frostbite.',
	'All of this blood: http://www.vampires.com/wordpress/wp-content/uploads/2009/08/Blood_Spatter.jpg',
	'Tongue.',
	'An unhinged ferris wheel rolling toward the sea.',
	'The corporations.',
	'A magic hippie love cloud.',
	'Fuck Mountain.',
	'Survivor\'s guilt.',
	'Me.',
	'A soulful rendition of "Man River".',
	'Intimacy problems.',
	'Spring break!.',
	'A sweaty, panting leather daddy.',
	'Another shot of morphine.',
	'A squadron of moles wearing aviator goggles.',
	'Bullshit.',
	'The Google.',
	'Pretty Pretty Princess Dress-Up Board Game.',
	'The new Radiohead album.',
	'An army of skeletons.',
	'A man in yoga pants with a ponytail and feather earrings.',
	'Mild autism.',
	'Nunchuck moves.',
	'An ether-soaked rag.',
	'A sweet spaceship.',
	'A 55-gallon drum of lube.',
	'The human body.',
	'The grey nutrient broth that sustains Mitt Romney.',
	'Tiny nipples.',
	'Power.',
	'Oncoming traffic.',
	'A dollop of sour cream.',
	'A slightly shittier parallel universe.',
	'My first kill.',
	'Graphic violence, adult language, and some sexual content.',
	'Fetal alcohol syndrome.',
	'The day the birds attacked.',
	'One Ring to rule them all.',
	'Grandpa\'s ashes.',
	'Basic human decency.',
	'A Burmese tiger pit.',
	'Death by Steven Seagal.',
	'The primal, ball-slapping sex your parents are having right now.',
	'A cat video so cute that your eyes roll back and your spine slides out of your anus.',
	'Cock.',
	'A cop who is also a dog.',
	'The way white people is.',
	'Reverse cowgirl.',
	'The Quesadilla Explosion Salad from Chili\'s.',
	'Actually getting shot, for real.',
	'Vietnam flashbacks.',
	'Nothing.',
	'Warm, velvety muppet sex.',
	'Self-flagellation.',
	'The systematic destruction of an entire people and their way of life.',
	'A boo-boo.',
	'The entire Internet.',
	'Some kind of bird-man.',
	'Indescribable loneliness.',
	'An ass disaster.',
	'All my friends dying.',
	'Some douche with an acoustic guitar.',
	'Flying robots that kill people.',
	'A greased-up Matthew McConaughey.',
	'An unstoppable wave of fire ants.',
	'An all-midget production of Shakespeare\'s "Richard III".',
	'The moist, demanding chasm of his mouth.',
	'Unlimited soup, salad, and breadsticks.',
	'Crying into the pages of Sylvia Plath.',
	'Velcro.',
	'A PowerPoint presentation.',
	'A surprising amount of hair.',
	'That ass.',
	'A pile of squirming bodies.',
	'Blood farts.',
	'Three months in the hole.',
	'A botched circumcision.',
	'The Land of Chocolate.',
	'A lamprey swimming up the toilet and latching onto your taint.',
	'A black male in his early 20s, last seen wearing a hoodie.',
	'Mufasa\'s death scene.',
	'Demonic possession.',
	'A spontaneous conga line.',
	'A vagina that leads to another dimension.',
	'Disco fever.',
	'The thin veneer of situational causality that underlies porn.',
	'Girls that always be textin\'.',
	'Moldy Bread.',
	'A plastic goat.',
	'Too many lemons.',
	'sudo make me a sandwich.',
	'I should buy a boat.',
	'An army of jtrucks clones.'

]

module.exports = whatArray;