var whoArray = [

	'An honest cop with nothing left to lose.',
	'Shapeshifters.',
	'Porn stars.',
	'72 virgins.',
	'Consultants.',
	'Former President George W. Bush.',
	'The Hamburglar.',
	'Kanye West.',
	'A middle-aged man on roller skates.',
	'Children on leashes.',
	'Gandhi.',
	'Customer service representatives.',
	'The Make-A-Wish Foundation.',
	'The Chinese gymnastics team.',
	'The Jews.',
	'Mr. Clean, right behind you.',
	'Republicans.',
	'Natalie Portman.',
	'Sean Connery.',
	'The hardworking Mexican.',
	'Altar boys.',
	'The Kool-Aid Man.',
	'RoboCop.',
	'Justin Bieber.',
	'Oompa-Loompas.',
	'Ghosts.',
	'John Wilkes Booth.',
	'Preteens.',
	'Darth Vader.',
	'Tom Cruise.',
	'Homeless people.',
	'Sperm whales.',
	'Pac-Man uncontrollably guzzling cum.',
	'A mime having a stroke.',
	'Hulk Hogan.',
	'God.',
	'Friends with benefits.',
	'Aaron Burr.',
	'Ronald Reagan.',
	'A sassy black woman.',
	'Mathletes.',
	'A tiny horse.',
	'William Shatner.',
	'Pedophiles.',
	'Poor people.',
	'The Übermensch.',
	'Sarah Palin.',
	'American Gladiators.',
	'The KKK.',
	'Genghis Khan.',
	'A monkey smoking a cigar.',
	'The terrorists.',
	'Britney Spears at 55.',
	'The Little Engine That Could.',
	'The Pope.',
	'White people.',
	'Keanu Reeves.',
	'Sean Penn.',
	'Nickelback.',
	'Kids with ass cancer.',
	'The South.',
	'Centaurs.',
	'Bill Nye the Science Guy.',
	'Black people.',
	'Bitches.',
	'The profoundly handicapped.',
	'Heartwarming orphans.',
	'MechaHitler.',
	'Michael Jackson.',
	'Guys who don\'t call.',
	'Muhammad (Praise Be Unto Him).',
	'Robert Downey, Jr.',
	'Kim Jong-il.',
	'Jewish fraternities.',
	'The token minority.',
	'Count Chocula.',
	'Italians.',
	'A fetus.',
	'Dick Cheney.',
	'Amputees.',
	'Christopher Walken.',
	'Nazis.',
	'Stephen Hawking talking dirty.',
	'Nicolas Cage.',
	'Glenn Beck being harried by a swarm of buzzards.',
	'Her Royal Highness, Queen Elizabeth II.',
	'Goblins.',
	'The Rev. Dr. Martin Luther King, Jr.',
	'Vikings.',
	'Hot people.',
	'Geese.',
	'Judge Judy.',
	'African children.',
	'Barack Obama.',
	'Asians who aren\'t good at math.',
	'Elderly Japanese men.',
	'Arnold Schwarzenegger.',
	'Friends who eat all the snacks.',
	'Goats eating cans.',
	'Morgan Freeman\'s voice.',
	'Women in yogurt commercials.',
	'Passable transvestites.',
	'Grandma.',
	'Party poopers.',
	'Hurricane Katrina.',
	'The gays.',
	'Men.',
	'The Amish.',
	'Cards Against Humanity.',
	'Lady Gaga.',
	'The milk man.',
	'A passionate Latino lover.',
	'A rival dojo.',
	'A woman scorned.',
	'Clams.',
	'Neil Patrick Harris.',
	'Bosnian chicken farmers.',
	'Nubile slave boys.',
	'Carnies.',
	'Enormous Scandinavian women.',
	'Gandalf.',
	'Genetically engineered super-soldiers.',
	'Hipsters.',
	'Jafar.',
	'Jean-Claude Van Damme.',
	'Ryan Gosling riding in on a white horse.',
	'Santa Claus.',
	'Sexy Siamese twins.',
	'The Fanta girls.',
	'The shambling corpse of Larry King.',
	'Zeus\'s sexual appetites.',
	'A sad fat dragon with no friends.',
	'Hillary Clinton\'s death stare.',
	'Loki, the trickster god.',
	'The corporations.',
	'Jeff Goldblum.',
	'A sweaty, panting leather daddy.',
	'A squadron of moles wearing aviator goggles.',
	'The Google.',
	'An army of skeletons.',
	'A man in yoga pants with a ponytail and feather earrings.',
	'Special musical guest, Cher.',
	'Boris the Soviet Love Hammer.',
	'Grandpa\'s ashes.',
	'A cop who is also a dog.',
	'Gay aliens.',
	'Samuel L. Jackson.',
	'Some kind of bird-man.',
	'Some douche with an acoustic guitar.',
	'Flying robots that kill people.',
	'A greased-up Matthew McConaughey.',
	'An unstoppable wave of fire ants.',
	'Roland the Farter, flatulist to the king.',
	'A black male in his early 20s, last seen wearing a hoodie.',
	'Bill Clinton, naked on a bearskin rug with a saxophone.',
	'The Harlem Globetrotters.',
	'My manservant, Claude.',
	'A plastic goat.',
	'An army of jtrucks clones.',
	'Kyle Yankan.',
	'Armchair Quarterbacks'

]

module.exports = whoArray;